Fix calendar in ISBN registration form (Basic Information page)
NatLibFi/identifier-services-ui pull request #134
Opened 2022-01-21 10:05 UTC by mvillivald

1. Switch calendar component from TextField (@material-ui/core) to KeyboardDatePicker (@material-ui/pickers) for now. In the future we should think about migrating to the new version of MUI library (v.5.x).
2. Add lang props to the date picker provider.
3. Fix data formats as requested.

2022-01-24 09:56 UTC, aatuny requested changes

2022-01-24 09:56 UTC, aatuny commented on src/frontend/components/form/isbnIsmnRegistrationForm/preview.js
> +						<ListComponent label={intl.formatMessage({id: 'listComponent.publicationTime'})} value={formatPublicationValue.publicationTime ? moment(formatPublicationValue.publicationTime).format('DD/MM/YYY
Use month as basis for accuracy when evaluating publication time.

2022-01-25 06:41 UTC, aatuny requested changes
Code is approved, but current calendar component usage arises two change requests:
- Allow current month to be selected
- While selecting the month, do not fallback to year selection but rather close the selection view

2022-01-25 10:29 UTC, mvillivald commented on src/frontend/components/form/isbnIsmnRegistrationForm/content.js
> +					min: moment(Date.now()).month() + 1 + '-' + moment(Date.now()).date() + '-' + moment(Date.now()).year(),
Changed this to `moment(Date.now()).format('YYYY-MM')`, so, I hope, now there should not be any problems with min date

2022-01-25 12:43 UTC, aatuny approved these changes

2022-01-25 14:17 UTC, merged