Fix authors page in ISBN form
NatLibFi/identifier-services-ui pull request #135
Opened 2022-01-25 10:50 UTC by mvillivald

1. Changed the appearance of the Authors page. The page is now divided into two blocks. One block is for form and buttons, and the other is for displaying the data in the list.
2. Now the form is more intuitive, the user can more clearly understand what roles have been added and which one belongs to a particular author.
3. One person can be added to several role categories

2022-01-28 11:27 UTC, aatuny requested changes

2022-01-28 13:23 UTC, villivald commented on src/frontend/components/ListComponent.js
> +export default connect(mapStateToProps)(ListComponent);
Done, connect is removed for now

2022-01-28 13:23 UTC, villivald commented on src/frontend/components/ListComponent.js
> +											Nimi:
Done

2022-01-28 13:24 UTC, villivald commented on src/frontend/components/form/constants.js
> +	{label: <FormattedMessage id="publicationRegistration.form.authors.role.authors"/>, value: 'tekijä'},
Done, I deleted the unneeded constant array

2022-01-28 13:24 UTC, villivald commented on src/frontend/components/form/render/renderContactDetail.js
> +			setErrors();
Done

2022-02-01 06:39 UTC, aatuny requested changes

2022-02-01 06:39 UTC, aatuny commented on src/frontend/components/form/render/renderContactDetail.js
> +							<h2>Tekijät</h2>
Use FormattedMessage to apply multilanguage support.

2022-02-01 06:39 UTC, aatuny commented on src/frontend/components/form/render/renderContactDetail.js
> +								{values && values.authors && values.authors.length ? null : 'Tekijöitä ei ole lisätty vielä, lisää tekijä täyttämällä tiedot ja painamalla "Lisää" nappia'}
Apply FormattedMessage to here also.

2022-02-01 06:39 UTC, aatuny commented on src/frontend/components/subComponents/cards/AuthorCard.js
> +							Nimi:
Apply FormattedMessage.

2022-02-01 06:39 UTC, aatuny commented on src/frontend/components/subComponents/cards/AuthorCard.js
> +		)) : 'Tekijöitä ei ole lisätty'
Apply FormattedMessage

2022-02-01 06:39 UTC, aatuny commented on src/frontend/components/subComponents/cards/AuthorCard.js
> +						<Typography className={classes.authorCardLabel}>Roolit:</Typography>
Apply FormattedMessage

2022-02-01 08:33 UTC, aatuny approved these changes

2022-02-01 08:34 UTC, merged